variables:
  Version: '1.0.5'
  # Major: '1'
  # Minor: '0'
  # Patch: '0'

trigger:
  tags:
    include:
      - '*.*.*'


pool:
  vmImage: ubuntu-latest


steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: echo '$BUILD_SOURCEBRANCHNAME'
      
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: '"$(Build.SourceBranch)"'

  - task: PowerShell@2
    displayName: Display version of app
    inputs:
      targetType: 'inline'
      script: 'Write-Host "Version of app: $(Build.SourceBranch)"' 


  - task: DotNetCoreCLI@2
    displayName: Pack Project
    inputs:
      command: 'pack'
      packagesToPack: '**/FastSharp.DependencyInjection.csproj'
      packDirectory: $(Build.ArtifactStagingDirectory)
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'BUILD_SOURCEBRANCHNAME'
  
    # - task: NuGetCommand@2
    #   inputs:
    #     command: 'push'
    #     packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    #     nuGetFeedType: 'external'
    #     publishFeedCredentials: 'Nuget.Org'



# stages:
#   - stage: Build
#     jobs:
#       - job: 'build_project'
#         steps:
          # - task: DotNetCoreCLI@2
          #   inputs:
          #     command: 'build'
          #     projects: '**/*.csproj'
          # - task: DotNetCoreCLI@2
          #   inputs:
          #     command: 'pack'
          #     packagesToPack: '**/*.csproj'
          #     packDirectory: $(Build.ArtifactStagingDirectory)
          #     versioningScheme: byPrereleaseNumber
          #     majorVersion: '$(Major)'
          #     minorVersion: '$(Minor)'
          #     patchVersion: '$(Patch)'


